import AppKit
import Foundation

/// Lucide icon helper: loads one of the rasterized lucide PNGs (Resources/
/// Icons, generated by scripts/icons_to_png.mjs) at the given point size.
/// The PNGs are black-on-transparent so template rendering tints them.
enum Lucide {
    private static var cache: [String: NSImage] = [:]

    @MainActor
    static func image(_ name: String, pointSize: CGFloat = 22) -> NSImage {
        let key = "\(name)-\(Int(pointSize))"
        if let hit = cache[key] { return hit }
        let size = NSSize(width: pointSize, height: pointSize)
        // Icons end up at the bundle root with .process("Resources") (flattened),
        // but also check Icons/ for future .copy setups.
        let bundle = Bundle.typieResources
        let url = bundle?.url(forResource: name, withExtension: "png", subdirectory: "Icons")
            ?? bundle?.url(forResource: name, withExtension: "png")
        guard let url, let source = NSImage(contentsOf: url) else {
            let fallback = NSImage(systemSymbolName: "questionmark", accessibilityDescription: nil) ?? NSImage()
            cache[key] = fallback
            return fallback
        }
        let image = NSImage(size: size)
        let rep = NSBitmapImageRep(data: source.tiffRepresentation ?? Data()) ?? NSBitmapImageRep()
        rep.size = size
        image.addRepresentation(rep)
        image.isTemplate = true
        cache[key] = image
        return image
    }
}