import AppKit
import Combine
import UniformTypeIdentifiers
import WebKit

/// Which flow the web view is hosting.
enum WebRoute: String {
    case onboarding
    case app
}

/// Hosts typie's web UI (built from app/webui, bundled at
/// Resources/webui/) inside a WKWebView, and bridges state both ways.
///
/// Swift -> JS: full state snapshots pushed as JSON into
/// `window.__typie.push(...)` whenever any store changes (coalesced).
/// JS -> Swift: actions via `webkit.messageHandlers.typie.postMessage`.
/// Standalone message-handler object: must be registered on the
/// WKWebViewConfiguration *before* the WKWebView is created (WebKit
/// ignores configuration changes afterwards), so it can't be the
/// controller itself — that would need self before super.init.
private final class ScriptBridge: NSObject, WKScriptMessageHandler {
    var onMessage: (([String: Any]) -> Void)?

    nonisolated func userContentController(
        _ userContentController: WKUserContentController,
        didReceive message: WKScriptMessage
    ) {
        guard message.name == "typie" else { return }
        MainActor.assumeIsolated {
            onMessage?(message.body as? [String: Any] ?? [:])
        }
    }
}

/// Serves the bundled web UI over typie:// so ES modules, fetch() and
/// friends work (they refuse file:// URLs). Paths map 1:1 into the
/// WebResources/webui/ folder inside the resource bundle.
private final class SchemeHandler: NSObject, WKURLSchemeHandler {
    private static let mimeTypes = [
        "html": "text/html", "js": "text/javascript", "mjs": "text/javascript",
        "css": "text/css", "json": "application/json", "svg": "image/svg+xml",
        "ttf": "font/ttf", "otf": "font/otf", "woff": "font/woff",
        "woff2": "font/woff2", "png": "image/png", "jpg": "image/jpeg",
        "jpeg": "image/jpeg", "gif": "image/gif", "webp": "image/webp",
        "ico": "image/x-icon", "wasm": "application/wasm", "map": "application/json",
        "wav": "audio/wav", "mp3": "audio/mpeg", "m4a": "audio/mp4",
        "mp4": "video/mp4", "aac": "audio/aac", "caf": "audio/caf", "flac": "audio/flac",
    ]

    func webView(_ webView: WKWebView, start task: WKURLSchemeTask) {
        guard let url = task.request.url,
              let root = WebUIController.webUIRoot
        else { return fail(task) }

        // strip query/fragment, resolve within the bundle folder only
        var components = URLComponents(url: url, resolvingAgainstBaseURL: false)!
        components.query = nil
        components.fragment = nil
        var relPath = percentDecode(components.url?.path ?? "/index.html")
        // URL paths always carry a leading "/" — strip it or prefix checks below
        // silently never match (this exact bug muted all transcript audio once)
        while relPath.hasPrefix("/") { relPath.removeFirst() }
        if relPath.isEmpty { relPath = "index.html" }

        // transcript audio lives OUTSIDE the bundle, in the data dir —
        // served so the web UI can scrub recordings word-by-word
        if relPath.hasPrefix("transcript-audio/") {
            return serveTranscriptAudio(task, url: url, name: String(relPath.dropFirst("transcript-audio/".count)))
        }

        let fileURL = root.appendingPathComponent(relPath)

        guard fileURL.standardizedFileURL.path.hasPrefix(root.standardizedFileURL.path),
            let data = try? Data(contentsOf: fileURL)
        else { return fail(task) }

        respond(task, url: url, data: data, ext: fileURL.pathExtension.lowercased(), rangeHeader: task.request.value(forHTTPHeaderField: "Range"))
    }

    /// Serve one stashed recording from <support>/transcripts/audio/<name>.
    /// Names are UUID.ext generated by TranscriptStore, but stay defensive:
    /// anything containing a path separator is rejected outright.
    private func serveTranscriptAudio(_ task: WKURLSchemeTask, url: URL, name: String) {
        guard !name.isEmpty, !name.contains("/"), !name.contains("..") else { return fail(task) }
        let fileURL = AppPaths.supportDir
            .appendingPathComponent("transcripts/audio", isDirectory: true)
            .appendingPathComponent(name)
        guard let data = try? Data(contentsOf: fileURL) else { return fail(task) }
        respond(task, url: url, data: data, ext: fileURL.pathExtension.lowercased(), rangeHeader: task.request.value(forHTTPHeaderField: "Range"))
    }

    /// Full 200 or byte-range 206 response (media elements seek via ranges).
    private func respond(_ task: WKURLSchemeTask, url: URL, data: Data, ext: String, rangeHeader: String?) {
        let mime = Self.mimeTypes[ext] ?? "application/octet-stream"

        if let header = rangeHeader, header.hasPrefix("bytes="),
           let range = Self.parseRange(header, total: data.count) {
            let slice = data.subdata(in: range.offset..<(range.offset + range.length))
            let response = HTTPURLResponse(
                url: url, statusCode: 206, httpVersion: nil,
                headerFields: [
                    "Content-Type": mime,
                    "Content-Length": String(range.length),
                    "Content-Range": "bytes \(range.offset)-\(range.offset + range.length - 1)/\(data.count)",
                    "Accept-Ranges": "bytes",
                    "Cache-Control": "no-store",
                ]
            )!
            task.didReceive(response)
            task.didReceive(slice)
            task.didFinish()
            return
        }

        // NB: no-store is load-bearing — without cache headers WebKit
        // heuristically caches typie:// responses, and a stale index.html
        // keeps serving an old UI bundle across app updates.
        let response = HTTPURLResponse(
            url: url, statusCode: 200, httpVersion: nil,
            headerFields: [
                "Content-Type": mime,
                "Content-Length": String(data.count),
                "Cache-Control": "no-store",
                "Content-Encoding": "identity",
            ]
        )!
        task.didReceive(response)
        task.didReceive(data)
        task.didFinish()
    }

    /// "bytes=a-b" / "bytes=a-" → (offset, length) clamped to the file
    private static func parseRange(_ header: String, total: Int) -> (offset: Int, length: Int)? {
        guard total > 0 else { return nil }
        let spec = header.dropFirst("bytes=".count).split(separator: "-")
        guard let first = spec.first, let offset = Int(first), offset < total else { return nil }
        let end = spec.count > 1 ? min(Int(spec[1]) ?? total - 1, total - 1) : total - 1
        guard end >= offset else { return nil }
        return (offset, end - offset + 1)
    }

    func webView(_ webView: WKWebView, stop task: WKURLSchemeTask) {}

    private func percentDecode(_ path: String) -> String {
        path.removingPercentEncoding ?? path
    }

    private func fail(_ task: WKURLSchemeTask) {
        AppLog.event("webui scheme: missing resource \(task.request.url?.path ?? "?")")
        task.didFailWithError(NSError(domain: "app.typie.webui", code: 404))
    }
}

@MainActor
final class WebUIController: NSObject, NSWindowDelegate {
    let window: NSWindow

    /// window closed by the user (or code)
    var onWillClose: (() -> Void)?
    /// explicit "done" from the onboarding flow
    var onComplete: (() -> Void)?
    /// became the key window (used to route transcripts to the practice box)
    var onBecomeKey: (() -> Void)?
    var onResignKey: (() -> Void)?

    private let route: WebRoute
    private let webView: WKWebView
    private let bridge = ScriptBridge()

    private var pageReady = false
    private var pendingPane: String?
    private var cancellables = Set<AnyCancellable>()
    private var permissionPoller: Timer?

    // hotkey capture ("click the keycap, press a modifier")
    private var captureMonitor: Any?
    private(set) var capturingHotkey = false

    // model-download ETA bookkeeping (mirrors the old onboarding math)
    private static var downloadStart: Date?

    private static let iso8601: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }()

    init(route: WebRoute, title: String, size: NSSize) {
        self.route = route

        // register the bridge BEFORE the web view exists — mandatory,
        // later additions to the config are ignored by WebKit
        let config = WKWebViewConfiguration()
        config.userContentController.add(bridge, name: "typie")
        config.setURLSchemeHandler(SchemeHandler(), forURLScheme: "typie")

        let view = WKWebView(frame: .zero, configuration: config)
        // no white flash before the first paint of the cream page
        view.setValue(false, forKey: "drawsBackground")
        view.underPageBackgroundColor = NSColor(red: 1, green: 0.992, blue: 0.968, alpha: 1)
        webView = view

        let win = NSWindow(
            contentRect: NSRect(origin: .zero, size: size),
            styleMask: [.titled, .closable],
            backing: .buffered,
            defer: false
        )
        win.title = title
        win.isReleasedWhenClosed = false
        win.backgroundColor = .white
        win.appearance = NSAppearance(named: .aqua)
        win.contentView = view
        win.center()

        // onboarding: seamless chrome — the web header IS the top bar, with
        // the traffic lights floating over the cream page (web side pads
        // its header to clear them)
        if route == .onboarding {
            win.styleMask.insert(.fullSizeContentView)
            win.titlebarAppearsTransparent = true
            win.titleVisibility = .hidden
            win.isMovableByWindowBackground = true
        }

        window = win

        super.init()

        bridge.onMessage = { [weak self] body in
            self?.handleMessage(body)
        }

        win.delegate = self
        view.navigationDelegate = self

        loadPage()
        observeStores()
        startPermissionPolling()
    }

    func present() {
        NSApp.activate(ignoringOtherApps: true)
        window.makeKeyAndOrderFront(nil)
        pushState()
    }

    /// Menu-driven pane switching on an already-open window.
    func showPane(_ pane: String) {
        guard pageReady else {
            pendingPane = pane
            return
        }
        webView.evaluateJavaScript("window.__typie.setPane && window.__typie.setPane('\(pane)')")
    }

    func setOnboardingStep(_ step: Int) {
        let clamped = max(0, min(step, 3))
        webView.evaluateJavaScript("window.__typie?.setStep && window.__typie.setStep(\(clamped))")
    }

    func setOnboardingRecheck(_ active: Bool) {
        webView.evaluateJavaScript("window.__typie?.setRecheck && window.__typie.setRecheck(\(active ? "true" : "false"))")
    }

    func close() {
        window.close()
    }

    // MARK: page load

    /// Root of the bundled web UI (WebResources/webui/, copied verbatim
    /// by SPM's .copy rule). Served to the WebView over a custom scheme —
    /// file:// URLs can't fetch ES modules (CORS), so we speak "typie://".
    static let webUIRoot: URL? = {
        let bundle = Bundle.typieResources
        let indexURL = bundle?.url(forResource: "index", withExtension: "html", subdirectory: "WebResources/webui")
            ?? bundle?.url(forResource: "index", withExtension: "html", subdirectory: "webui")
            ?? bundle?.url(forResource: "index", withExtension: "html")
        return indexURL?.deletingLastPathComponent()
    }()

    private func loadPage() {
        guard Self.webUIRoot != nil else {
            AppLog.event("webui: index.html NOT FOUND in resource bundle — window will be blank")
            return
        }
        webView.load(URLRequest(url: URL(string: "typie://webui/index.html")!))
    }

    // MARK: state observation

    private func observeStores() {
        SettingsStore.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        StatsStore.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        HistoryStore.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        ModelManager.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        DiarizeStore.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        NoteStore.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        TranscriptStore.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        MeetingAIService.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        DictationController.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
        MeetingController.shared.objectWillChange
            .sink { [weak self] _ in self?.schedulePush() }
            .store(in: &cancellables)
    }

    /// Permissions don't publish — poll while the window exists so the
    /// onboarding badges flip the moment the user approves in System Settings.
    /// Poll every 2s (was 0.7s — caused jank) and only pushes if permissions changed.
    private var lastPermissionSnapshot: String = ""
    private func startPermissionPolling() {
        permissionPoller = Timer.scheduledTimer(withTimeInterval: 2.0, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                guard let self else { return }
                let snap = "\(AudioCapture.micPermissionGranted())-\(HotkeyMonitor.accessibilityGranted(prompt: false))-\(SystemAudioRecorder.permissionGranted())"
                if snap != self.lastPermissionSnapshot {
                    self.lastPermissionSnapshot = snap
                    self.pushState()
                }
            }
        }
    }

    private func schedulePush() {
        // coalesce bursts (diarize progress ticks fire many times a second,
        // and each push serializes the whole library) — at most ~8 pushes/sec
        guard !pushPending else { return }
        pushPending = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) { [weak self] in
            self?.pushPending = false
            self?.pushState()
        }
    }

    private var pushPending = false

    private func pushState() {
        guard pageReady, webView.window != nil else { return }

        let settings = SettingsStore.shared
        let stats = StatsStore.shared.snapshot
        let controller = DictationController.shared

        var state: [String: Any] = [
            "route": route.rawValue,
            "variant": AppVariant.isDev ? "dev" : "prod",
            "settings": [
                "hotkey": settings.hotkey.rawValue,
                "hotkeyShort": settings.hotkey.shortLabel,
                "triggerMode": settings.triggerMode.bridgeID,
                "historyEnabled": settings.historyEnabled,
                "launchAtLogin": settings.launchAtLogin,
                "notesKeepAudio": settings.notesKeepAudio,
                "meetingMixMic": settings.meetingMixMic,
                "transcriptsKeepAudio": settings.transcriptsKeepAudio,
            ],
            "permissions": [
                "mic": AudioCapture.micPermissionGranted(),
                "ax": HotkeyMonitor.accessibilityGranted(prompt: false),
                "screen": SystemAudioRecorder.permissionGranted(),
            ],
            "model": modelStatusDict(),
            "modelsExist": ModelManager.modelsExist(),
            "meeting": [
                "isCapturing": MeetingController.shared.isCapturing,
                "processing": MeetingController.shared.processing,
                "startedAt": MeetingController.shared.startedAt.map { Self.iso8601.string(from: $0) } ?? "",
            ],
            "stats": [
                "totalWords": stats.totalWords,
                "totalDictations": stats.totalDictations,
                "totalAudioSeconds": stats.totalAudioSeconds,
                "avgLatencyMs": stats.totalDictations > 0
                    ? stats.totalTranscribeMs / Double(stats.totalDictations) : 0,
            ],
            "history": HistoryStore.shared.entries.map { entry in
                [
                    "id": entry.id.uuidString,
                    "text": entry.text,
                    "date": Self.iso8601.string(from: entry.date),
                    "latencyMs": entry.latencyMs,
                    "hasAudio": entry.audioFile != nil,
                ] as [String: Any]
            },
            "notes": NoteStore.shared.notes.map { note in
                [
                    "id": note.id.uuidString,
                    "text": note.text,
                    "date": Self.iso8601.string(from: note.date),
                    "durationSeconds": note.durationSeconds,
                    "pinned": note.pinned,
                    "hasAudio": note.audioFile != nil,
                ] as [String: Any]
            },
            "transcripts": TranscriptStore.shared.transcripts.map { transcript in
                // METADATA ONLY — turns/words made every push O(library) on
                // the main thread and froze the whole UI during processing.
                // The detail pane fetches one full transcript via "transcriptGet".
                [
                    "id": transcript.id.uuidString,
                    "fileName": transcript.fileName,
                    "date": Self.iso8601.string(from: transcript.date),
                    "durationSeconds": transcript.durationSeconds,
                    "speakerCount": transcript.speakerCount,
                    "elapsedMs": transcript.elapsedMs,
                    "isMeeting": transcript.isMeeting,
                    "hasAudio": transcript.audioFile != nil,
                    "audioUrl": transcript.audioFile.map { "transcript-audio/\($0)" } ?? "",
                    "turnCount": transcript.turns.count,
                    "preview": (transcript.aiSummary ?? String(transcript.turns.first?.text.prefix(120) ?? "")),
                    "speakerNames": Dictionary(uniqueKeysWithValues: transcript.speakerNames.map { (String($0.key), $0.value) }),
                    "aiTitle": transcript.aiTitle ?? "",
                    "aiSummary": transcript.aiSummary ?? "",
                    "aiStatus": transcript.aiStatus ?? "",
                    "aiEngine": transcript.aiEngine ?? "",
                    "aiTopics": (transcript.aiTopics ?? []).map { t in ["title": t.title, "start": t.startSeconds, "summary": t.summary] as [String: Any] },
                    "aiSections": (transcript.aiSections ?? []).map { s in ["title": s.title, "start": s.startSeconds, "ts": s.timestampLabel, "points": s.points.map { p in ["text": p.text, "start": p.startSeconds] as [String: Any] }] as [String: Any] },
                    "aiQuotes": (transcript.aiQuotes ?? []).map { q in ["text": q.text, "speaker": q.speaker, "start": q.startSeconds, "ts": q.timestampLabel] as [String: Any] },
                    "aiActions": (transcript.aiActions ?? []).map { a in ["speaker": a.speaker, "text": a.text, "start": a.startSeconds, "ts": a.timestampLabel] as [String: Any] },
                    "aiProgress": transcript.aiProgress ?? -1,
                ] as [String: Any]
            },
            "aiAvailable": MeetingAIService.shared.isSupported,
            "dictation": [
                "phase": phaseString(controller.phase),
                "lastMs": phaseMs(controller.phase),
                "transcript": controller.lastTranscript ?? "",
            ],
            "capturingHotkey": capturingHotkey,
            "eta": etaText(),
            "transcribe": transcribeStateDict(),
            "storage": Self.storageDict(),
        ]

        guard var jsonData = try? JSONSerialization.data(withJSONObject: state),
              var script = String(data: jsonData, encoding: .utf8)
        else { return }

        // U+2028/U+2029 are valid JSON but break JS string literals
        script = script
            .replacingOccurrences(of: "\u{2028}", with: "\\u2028")
            .replacingOccurrences(of: "\u{2029}", with: "\\u2029")

        webView.evaluateJavaScript("window.__typie && __typie.push(\(script))")
    }

    /// Local-footprint numbers for the sidebar's privacy meter: everything
    /// typie keeps (models + notes + transcripts + history) vs. the disk.
    /// Cached for 10s to avoid enumerating on every push (was causing jank).
    private static var cachedStorage: (dict: [String:Any], at: Date)?
    private static func storageDict() -> [String: Any] {
        if let c = cachedStorage, Date().timeIntervalSince(c.at) < 10 { return c.dict }
        let used = dirSize(AppPaths.supportDir) + dirSize(AppPaths.modelsRoot)
        let free = (try? FileManager.default.attributesOfFileSystem(forPath: "/")[.systemFreeSize] as? Int64) ?? 0
        let total = (try? FileManager.default.attributesOfFileSystem(forPath: "/")[.systemSize] as? Int64) ?? 0
        let dict: [String:Any] = ["usedBytes": used, "freeBytes": Int(free), "totalBytes": Int(total)]
        cachedStorage = (dict, Date())
        return dict
    }

    private static func dirSize(_ url: URL) -> Int {
        // skip hidden and package contents for speed
        guard let enumerator = FileManager.default.enumerator(
            at: url, includingPropertiesForKeys: [.fileSizeKey, .isRegularFileKey], options: [.skipsHiddenFiles])
        else { return 0 }
        var total = 0
        for case let fileURL as URL in enumerator {
            let vals = try? fileURL.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
            if vals?.isRegularFile == true { total += vals?.fileSize ?? 0 }
            // cap early to keep UI snappy on huge libraries
            if total > 50*1024*1024*1024 { break }
        }
        return total
    }

    private func modelStatusDict() -> [String: Any] {
        switch ModelManager.shared.status {
        case .notDownloaded:
            return ["status": "notDownloaded", "fraction": 0.0, "error": ""]
        case .downloading(let fraction):
            return ["status": "downloading", "fraction": fraction, "error": ""]
        case .loading:
            return ["status": "loading", "fraction": 0.98, "error": ""]
        case .ready:
            return ["status": "ready", "fraction": 1.0, "error": ""]
        case .failed(let message):
            return ["status": "failed", "fraction": 0.0, "error": message]
        }
    }

    // MARK: transcribe pane (batch diarization)

    private struct DropUpload {
        let name: String
        var data = Data()
    }

    private var dropUpload: DropUpload?

    private func transcribeStateDict() -> [String: Any] {
        let store = DiarizeStore.shared
        store.refreshModelState()

        let model: [String: Any]
        switch store.modelState {
        case .unknown:
            model = ["state": "unknown", "fraction": 0.0, "error": ""]
        case .notDownloaded:
            model = ["state": "notDownloaded", "fraction": 0.0, "error": ""]
        case .downloading(let fraction):
            model = ["state": "downloading", "fraction": fraction, "error": ""]
        case .compiling:
            model = ["state": "compiling", "fraction": 1.0, "error": ""]
        case .ready:
            model = ["state": "ready", "fraction": 1.0, "error": ""]
        case .failed(let message):
            model = ["state": "failed", "fraction": 0.0, "error": message]
        }

        var dict: [String: Any] = [
            "model": model,
            "downloadMB": DiarizeStore.downloadSizeMB,
            "busy": store.busy,
            "stage": store.stage,
            "progress": store.progress.map(NSNumber.init(value:)) ?? NSNull(),
            "eta": store.etaText,
            "queued": DiarizeStore.shared.queuedCount,
            "queue": DiarizeStore.shared.queueDict,
            "error": store.errorText ?? "",
        ]

        if let r = store.result {
            dict["result"] = [
                "fileName": r.fileName,
                "durationSeconds": r.durationSeconds,
                "speakerCount": r.speakerCount,
                "elapsedMs": r.elapsedMs,
                "plainTranscript": r.plainTranscript,
                "turns": r.turns.map { turn in
                    [
                        "speaker": turn.speakerIndex,
                        "start": turn.startSeconds,
                        "end": turn.endSeconds,
                        "text": turn.text,
                    ] as [String: Any]
                },
            ] as [String: Any]
        }
        return dict
    }

    private func presentAudioOpenPanel() {
        // no busy guard — extra picks just line up in the queue
        let panel = NSOpenPanel()
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = true
        panel.allowedContentTypes = [.audio, .movie]
        panel.message = "choose audio to transcribe with speaker labels"
        panel.beginSheetModal(for: window) { [weak self] response in
            guard response == .OK else { return }
            for url in panel.urls {
                DiarizeStore.shared.submit(url: url, isMeeting: false, owned: false)
            }
            _ = self // controller keeps the sheet's parent window alive
        }
    }

    /// Drag-and-drop arrives as a chunked base64 upload (WKWebView gives JS
    /// File objects without paths), which we reassemble into a temp file.
    /// Stage a completed chunk-upload into typie's own data dir (a persistent
    /// staging copy — NOT tmp), then enqueue it. The store adopts the staged
    /// file by move, so every transcript keeps its own unique audio copy.
    private func finishDrop(_ upload: DropUpload) {
        let ext = (upload.name as NSString).pathExtension
        let safeExt = ext.isEmpty ? "wav" : ext
        let displayName = upload.name
        let stagedURL = TranscriptStore.uploadsDir
            .appendingPathComponent("\(UUID().uuidString).\(safeExt)")
        // uploads can be hundreds of MB — stage the file off the main thread
        Task.detached(priority: .userInitiated) { [weak self] in
            do {
                try upload.data.write(to: stagedURL)
            } catch {
                AppLog.event("transcribe: failed to stage dropped file — \(error.localizedDescription)")
                return
            }
            await MainActor.run { [weak self] in
                self?.enqueueTranscribe(url: stagedURL, name: displayName)
            }
        }
    }

    private func enqueueTranscribe(url: URL, name: String) {
        DiarizeStore.shared.submit(url: url, isMeeting: false, owned: true, displayName: name)
    }

    // MARK: transcribe job queue (multiple uploads processed back-to-back)
    // the queue itself lives in DiarizeStore so meetings + uploads share it

    private static func uuid(from body: [String: Any]) -> UUID? {
        (body["id"] as? String).flatMap(UUID.init(uuidString:))
    }

    private func phaseString(_ phase: DictationPhase) -> String {
        switch phase {
        case .idle: return "idle"
        case .listening: return "listening"
        case .transcribing: return "transcribing"
        case .done: return "done"
        }
    }

    private func phaseMs(_ phase: DictationPhase) -> Double {
        if case .done(let ms) = phase { return ms }
        return -1
    }

    /// Rough ETA from observed download rate so far.
    private func etaText() -> String {
        guard let start = Self.downloadStart else { return "" }
        let elapsed = -start.timeIntervalSinceNow
        let fraction = ModelManager.shared.progressFraction
        guard elapsed > 3, fraction > 0.03, fraction < 1 else { return "" }
        let remaining = elapsed / fraction * (1 - fraction)
        if remaining >= 90 {
            return String(format: "about %d min left", Int((remaining / 60).rounded()))
        } else {
            return String(format: "about %d sec left", max(5, Int((remaining / 10).rounded() * 10)))
        }
    }

    // MARK: hotkey capture

    private func startHotkeyCapture() {
        guard captureMonitor == nil else { return }
        capturingHotkey = true
        pushState()
        captureMonitor = NSEvent.addLocalMonitorForEvents(matching: [.flagsChanged, .keyDown]) {
            [weak self] event in
            MainActor.assumeIsolated {
                guard let self else { return event }
                return self.handleCaptureEvent(event)
            }
        }
    }

    private func handleCaptureEvent(_ event: NSEvent) -> NSEvent? {
        switch event.type {
        case .flagsChanged:
            if let key = HotkeyKey.fromKeyCode(Int(event.keyCode)) {
                SettingsStore.shared.hotkey = key
                stopHotkeyCapture()
                return nil // swallow the modifier so it doesn't trigger menus/dictation
            }
            return event
        case .keyDown:
            if Int(event.keyCode) == 53 { // esc cancels
                stopHotkeyCapture()
                return nil
            }
            return event
        default:
            return event
        }
    }

    private func stopHotkeyCapture() {
        capturingHotkey = false
        if let monitor = captureMonitor {
            NSEvent.removeMonitor(monitor)
        }
        captureMonitor = nil
        pushState()
    }

    // MARK: teardown

    private func tearDown() {
        permissionPoller?.invalidate()
        permissionPoller = nil
        if let monitor = captureMonitor {
            NSEvent.removeMonitor(monitor)
            captureMonitor = nil
        }
        capturingHotkey = false
        webView.configuration.userContentController.removeScriptMessageHandler(forName: "typie")
        cancellables.removeAll()
    }

    deinit {
        // timers/monitors are torn down in windowWillClose(_:); nothing
        // main-actor-isolated happens here
    }

    // MARK: NSWindowDelegate forwarding

    nonisolated func windowWillClose(_ notification: Notification) {
        Task { @MainActor [weak self] in
            guard let self else { return }
            self.tearDown()
            self.onWillClose?()
        }
    }

    nonisolated func windowDidBecomeKey(_ notification: Notification) {
        Task { @MainActor [weak self] in self?.onBecomeKey?() }
    }

    nonisolated func windowDidResignKey(_ notification: Notification) {
        Task { @MainActor [weak self] in self?.onResignKey?() }
    }
}

// MARK: - JS -> Swift actions

extension WebUIController: WKNavigationDelegate {
    private func handleMessage(_ body: [String: Any]) {
        let type = body["type"] as? String ?? ""

        switch type {
        case "ready":
            pageReady = true
            AppLog.event("webui: page ready (\(route.rawValue))")
            if let pane = pendingPane {
                pendingPane = nil
                showPane(pane)
            }
            pushState()

        case "requestMicPermission":
            AudioCapture.requestMicPermission { [weak self] _ in
                self?.pushState()
            }

        case "requestAccessibility":
            _ = HotkeyMonitor.accessibilityGranted(prompt: true)

        case "requestScreenPermission":
            SystemAudioRecorder.requestPermission()
            // give meeting controller a chance to start after permission granted
            DispatchQueue.main.asyncAfter(deadline: .now()+0.6) { [weak self] in self?.pushState() }

        case "toggleNoteRecording":
            NoteStore.shared.toggleRecord()

        case "toggleMeetingRecording":
            MeetingController.shared.toggle()

        case "revealStorage":
            // the button in the sidebar footer: show the data folder in Finder
            NSWorkspace.shared.open(AppPaths.supportDir)

        case "startModelDownload":
            if !ModelManager.modelsExist() { Self.downloadStart = Date() }
            Task { await ModelManager.shared.downloadAndLoad() }

        case "startDiarizerDownload":
            Task { await DiarizeStore.shared.downloadAndLoad() }

        case "transcribeChooseFile":
            presentAudioOpenPanel()

        case "transcribeDropBegin":
            guard let name = body["name"] as? String,
                body["totalChunks"] != nil
            else { return }
            dropUpload = DropUpload(name: name)

        case "transcribeDropChunk":
            guard dropUpload != nil, body["index"] != nil,
                let b64 = body["b64"] as? String,
                let chunk = Data(base64Encoded: b64)
            else { return }
            dropUpload?.data.append(chunk)

        case "transcribeDropEnd":
            guard let upload = dropUpload else { return }
            dropUpload = nil
            guard !upload.data.isEmpty else { return }
            finishDrop(upload)

        case "setSetting":
            applySetting(key: body["key"] as? String, value: body["value"])

        case "startHotkeyCapture":
            startHotkeyCapture()

        case "completeOnboarding":
            onComplete?()

        case "onboardingReadyStep":
            DictationController.shared.startMonitoring()

        case "copy":
            if let text = body["text"] as? String {
                NSPasteboard.general.clearContents()
                NSPasteboard.general.setString(text, forType: .string)
            }

        case "notesTogglePin":
            if let id = Self.uuid(from: body) { NoteStore.shared.togglePin(id) }

        case "notesDelete":
            if let id = Self.uuid(from: body) { NoteStore.shared.delete(id) }

        case "noteExport":
            if let id = Self.uuid(from: body) {
                NoteStore.shared.export(id, format: body["format"] as? String ?? "md")
            }

        case "transcriptsDelete":
            if let id = Self.uuid(from: body) { TranscriptStore.shared.delete(id) }

        case "historyDelete":
            if let id = Self.uuid(from: body) { HistoryStore.shared.remove(id) }

        case "historyClear":
            HistoryStore.shared.clear()

        case "transcriptsRename":
            if let id = Self.uuid(from: body), let name = body["name"] as? String {
                TranscriptStore.shared.rename(id, name: name)
            }

        case "transcriptsRenameSpeaker":
            if let id = Self.uuid(from: body),
               let index = body["index"] as? Int,
               let name = body["name"] as? String {
                TranscriptStore.shared.renameSpeaker(id, index: index, name: name)
            }

        case "transcriptExport":
            if let id = Self.uuid(from: body) {
                TranscriptStore.shared.export(id, format: body["format"] as? String ?? "md")
            }

        case "transcriptGet":
            // full transcript (turns + word timings) for the open detail pane
            if let id = Self.uuid(from: body),
               let t = TranscriptStore.shared.transcripts.first(where: { $0.id == id }) {
                let payload: [String: Any] = [
                    "id": id.uuidString,
                    "fileName": t.fileName,
                    "date": Self.iso8601.string(from: t.date),
                    "durationSeconds": t.durationSeconds,
                    "speakerCount": t.speakerCount,
                    "isMeeting": t.isMeeting,
                    "hasAudio": t.audioFile != nil,
                    "audioUrl": t.audioFile.map { "transcript-audio/\($0)" } ?? "",
                    "speakerNames": Dictionary(uniqueKeysWithValues: t.speakerNames.map { (String($0.key), $0.value) }),
                    "aiTitle": t.aiTitle ?? "",
                    "aiSummary": t.aiSummary ?? "",
                    "aiStatus": t.aiStatus ?? "",
                    "aiEngine": t.aiEngine ?? "",
                    "aiGeneratedAt": t.aiGeneratedAt.map { Self.iso8601.string(from: $0) } ?? "",
                    "aiTopics": (t.aiTopics ?? []).map { topic in ["title": topic.title, "start": topic.startSeconds, "summary": topic.summary] as [String: Any] },
                    "aiSections": (t.aiSections ?? []).map { s in ["title": s.title, "start": s.startSeconds, "ts": s.timestampLabel, "points": s.points.map { p in ["text": p.text, "start": p.startSeconds] as [String: Any] }] as [String: Any] },
                    "aiQuotes": (t.aiQuotes ?? []).map { q in ["text": q.text, "speaker": q.speaker, "start": q.startSeconds, "ts": q.timestampLabel] as [String: Any] },
                    "aiActions": (t.aiActions ?? []).map { a in ["speaker": a.speaker, "text": a.text, "start": a.startSeconds, "ts": a.timestampLabel] as [String: Any] },
                    "aiProgress": t.aiProgress ?? -1,
                    "turns": t.turns.map { turn in
                        [
                            "speaker": turn.speakerIndex,
                            "start": turn.startSeconds,
                            "end": turn.endSeconds,
                            "text": turn.text,
                            "words": (turn.words ?? []).map { w in
                                ["text": w.text, "start": w.start, "end": w.end]
                            },
                        ] as [String: Any]
                    },
                ]
                // stale heuristic summary + the real model now available →
                // quietly regenerate so opening an old transcript upgrades it
                if t.aiEngine == "heuristic", t.aiStatus == "done",
                   MeetingAIService.shared.isSupported {
                    AppLog.event("ai: upgrading heuristic summary to FoundationModels — \(t.fileName)")
                    Task { await TranscriptStore.shared.generateAI(for: id) }
                }
                if let data = try? JSONSerialization.data(withJSONObject: payload),
                   var json = String(data: data, encoding: .utf8) {
                    json = json.replacingOccurrences(of: "\u{2028}", with: "\\u2028")
                        .replacingOccurrences(of: "\u{2029}", with: "\\u2029")
                    webView.evaluateJavaScript("window.__typie.setTranscript && window.__typie.setTranscript(\(json))")
                }
            }

        case "transcriptGenerateAI":
            // explicit user action — heuristics allowed when the real model
            // is unavailable, because they asked for it
            if let id = Self.uuid(from: body) {
                Task { await TranscriptStore.shared.generateAI(for: id, allowHeuristic: true) }
            }

        case "transcriptClearAI":
            if let id = Self.uuid(from: body) {
                TranscriptStore.shared.clearAI(for: id)
            }

        case "log":
            AppLog.event("webui js: \(body["message"] as? String ?? "?")")

        default:
            AppLog.event("webui: unknown message type '\(type)'")
        }
    }

    private func applySetting(key: String?, value: Any?) {
        let settings = SettingsStore.shared
        switch key {
        case "triggerMode":
            if let raw = value as? String, let mode = TriggerModeBridge(rawValue: raw) {
                settings.triggerMode = mode.native
            }
        case "historyEnabled":
            if let bool = value as? Bool { settings.historyEnabled = bool }
        case "launchAtLogin":
            if let bool = value as? Bool { settings.launchAtLogin = bool }
        case "notesKeepAudio":
            if let bool = value as? Bool { settings.notesKeepAudio = bool }
        case "meetingMixMic":
            if let bool = value as? Bool { settings.meetingMixMic = bool }
        case "transcriptsKeepAudio":
            if let bool = value as? Bool { settings.transcriptsKeepAudio = bool }
        default:
            AppLog.event("webui: unknown setting '\(key ?? "")'")
        }
    }

    // MARK: navigation policy (open external links outside the app)

    nonisolated func webView(
        _ webView: WKWebView,
        decidePolicyFor navigationAction: WKNavigationAction,
        decisionHandler: @escaping (WKNavigationActionPolicy) -> Void
    ) {
        if let url = navigationAction.request.url,
           url.scheme == "http" || url.scheme == "https" {
            NSWorkspace.shared.open(url)
            decisionHandler(.cancel)
            return
        }
        decisionHandler(.allow)
    }
}

// MARK: - bridge-safe enums

/// Lowercase ids shared with the JS side (TriggerPicker.svelte).
enum TriggerModeBridge: String {
    case both
    case hold
    case toggle

    var native: TriggerMode {
        switch self {
        case .both: return .both
        case .hold: return .hold
        case .toggle: return .toggle
        }
    }
}

extension TriggerMode {
    var bridgeID: String {
        switch self {
        case .both: return "both"
        case .hold: return "hold"
        case .toggle: return "toggle"
        }
    }
}
