import { chromium } from 'playwright-core';
const exe = `${process.env.HOME}/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing`;
const browser = await chromium.launch({ executablePath: exe });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
await page.evaluate(() => { for (const el of document.querySelectorAll('body *')) { if (getComputedStyle(el).position === 'fixed') el.style.visibility = 'hidden'; } });
await page.addStyleTag({ content: `*,*::before,*::after{animation-play-state:paused !important;}` });
const card = page.locator('#features .c4 .callPreview');
await card.scrollIntoViewIfNeeded();
await page.waitForTimeout(900);
await card.screenshot({ path: '/tmp/capture.png' });
await browser.close();
